#指定端口号
server:
  port: 8080
spring:
#thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
    check-template-location: true
  #数据库配置
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yylife?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
# 连接池
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
#mybatis 配置
mybatis:
  type-aliases-package: com.example.demo3h.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro配置
#solr配置
#监听器